name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (if you're using Node.js for your site)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies (if your project uses npm/yarn)
        run: npm install  # or `yarn install` if using yarn

      - name: Build project (adjust according to your build process)
        run: npm run build  # Replace with your specific build command if needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Make sure this points to the directory where your built site is located
