name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.name "G34hWeatherSpotter"
          git config --global user.email "G34hWeatherSpotter@users.noreply.github.com"

      - name: Create gh-pages branch if it doesn't exist
        run: |
          git fetch
          git checkout --orphan gh-pages || git checkout gh-pages
          git reset --hard

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # The root of the repository (adjust if necessary to a different directory)

      - name: Commit and push to gh-pages
        run: |
          git add .
          git commit -m "Deploy updates"
          git push --force origin gh-pages  # Force push to the gh-pages branch
