name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploys whenever a change is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Deploy to GitHub Pages
        run: |
          mkdir gh-pages
          cp -R * gh-pages/
          git config --global user.name "G34hWeatherSpotter"
          git config --global user.email "G34hWeatherSpotter@users.noreply.github.com"
          cd gh-pages
          git init
          git add .
          git commit -m "Deploy updates"
          git branch -M main
          git remote add origin https://github.com/G34hWeatherSpotter/Weather-alerts.git
          git push --force --set-upstream origin main
