name: Update Weather Alerts

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  update-alerts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the fetch_alerts script
      run: python fetch_alerts.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git pull origin main  # Pull the latest changes
        git add alerts.txt
        git commit -m "Update alerts.txt with new weather alerts"
        git push origin main
