name: Auto-Update Weather Alerts

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes to fetch new alerts
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  update_alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run alert script
        run: python update_alerts.py  # This will fetch and update alerts.txt with new data

      - name: Commit and push updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for pushing changes
        run: |
          git config --global user.name "G34hWeatherSpotter"
          git config --global user.email "G34hWeatherSpotter@users.noreply.github.com"
          git add alerts.txt  # Add updated alerts.txt to the commit
          git commit -m "Updated weather alerts" || echo "No changes to commit"  # Commit the update
          git push  # Push the changes to the repository
